// examples/basic-app/src/web/layout.tsx
import React from 'react';
import {Metadata, router} from "vatts/react"
import './globals.css';
interface LayoutProps {
    children: React.ReactNode;
}


export const metadata: Metadata = {
    title: "Vatts JS | The Fast and Simple Web Framework for React",
    description: "The fastest and simplest web framework for React! Start building high-performance web applications today with Vatts JS.",
    keywords: ["Vatts JS", "web framework", "React", "JavaScript", "TypeScript", "web development", "fast", "simple", "SSR", "frontend"],
    author: "Vatts JS Team",
};

export default function Layout({ children }: LayoutProps) {
    return (
        <>{children}</>
    );
}

// examples/my-vatts-app/src/web/layout.vue
<script lang="ts">
import type { Metadata } from "vatts/vue";

export const metadata: Metadata = {
  title: "Vatts JS | The Fast and Simple Web Framework for React",
  description: "The fastest and simplest web framework for React! Start building high-performance web applications today with Vatts JS.",
  keywords: ["Vatts JS", "web framework", "React", "JavaScript", "TypeScript", "web development", "fast", "simple", "SSR", "frontend"],
  author: "Vatts JS Team",
};
</script>

<script setup lang="ts">
import './globals.css';
</script>

<template>
  <slot />
</template>
