// packages/vatts/src/client/image/Image.tsx
import React, { CSSProperties } from 'react';

interface VattsImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
    src: string;
    width?: number | string;
    height?: number | string;
    quality?: number;
    priority?: boolean;
}

const Image: React.FC<VattsImageProps> = ({
                                                   src,
                                                   width,
                                                   height,
                                                   quality = 75,
                                                   priority = false,
                                                   className,
                                                   style,
                                                   alt = "",
                                                   ...props
                                               }) => {
    function getBaseUrl(): string | null {
        if (typeof window === "undefined") return null
        return window.location.origin
    }

    const baseUrl = getBaseUrl()
    // Se a imagem for Base64 (pequena) ou externa (http), não otimizamos via backend local
    const isOptimizable = src && src.startsWith && !src.startsWith('data:') && ((baseUrl && src.startsWith(baseUrl)) || !src.startsWith('http'));
    function optimizeSrc(src: string, baseUrl: string | null) {
        if (!baseUrl) return src

        if (src.startsWith(baseUrl)) {
            return src.slice(baseUrl.length) || '/'
        }

        return src
    }

    let optimizedSrc = optimizeSrc(src, baseUrl);
    if (isOptimizable) {
        const params = new URLSearchParams();
        params.set('url', optimizedSrc);

        // Tratamento inteligente para remover "px" se o usuário passar string
        if (width) {
            const w = String(width).replace('px', '');
            if (!isNaN(Number(w))) params.set('w', w);
        }


         if (height) {
           const h = String(height).replace('px', '');
           if (!isNaN(Number(h))) params.set('h', h);
        }

        if (quality) params.set('q', quality.toString());

        optimizedSrc = `/_vatts/image?${params.toString()}`;
    }

    // Estilos base para prevenir layout shift se dimensões forem fornecidas
    const baseStyle: CSSProperties = {
        // Se width for numérico, assume pixels, senão usa o valor string (ex: 100%)
        width: width ? (typeof width === 'number' ? `${width}px` : width) : 'auto',
        height: height ? (typeof height === 'number' ? `${height}px` : height) : 'auto',
        ...style,
    };

    return (
        <img
            {...props}
            src={optimizedSrc}
            alt={alt}
            loading={priority ? 'eager' : 'lazy'}
            decoding={priority ? 'sync' : 'async'}
            width={typeof width === 'string' ? width.replace('px', '') : width}
            height={typeof height === 'string' ? height.replace('px', '') : height}
            className={`vatts-image ${className || ''}`}
            style={baseStyle}
        />
    );
};

export default Image;

// packages/vatts/src/vue/image/Image.vue
<!--
 * This file is part of the Vatts.js Project.
 * Copyright (c) 2026 itsmuzin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 -->

<script setup lang="ts">
import { computed, type StyleValue } from 'vue';

interface VattsImageProps {
  src: string;
  width?: number | string;
  height?: number | string;
  quality?: number;
  priority?: boolean;
  alt?: string;
}

const props = withDefaults(defineProps<VattsImageProps>(), {
  quality: 75,
  priority: false,
  alt: ""
});

const getBaseUrl = (): string | null => {
  if (typeof window === "undefined") return null;
  return window.location.origin;
};

const optimizedSrc = computed(() => {
  const baseUrl = getBaseUrl();
  const { src, quality, width, height } = props;

  // Se a imagem for Base64 (pequena) ou externa (http), não otimizamos via backend local
  const isOptimizable = src && typeof src === 'string' && !src.startsWith('data:') &&
      ((baseUrl && src.startsWith(baseUrl)) || !src.startsWith('http'));

  if (!isOptimizable) return src;

  let path = src;
  if (baseUrl && path.startsWith(baseUrl)) {
    path = path.slice(baseUrl.length) || '/';
  }

  const params = new URLSearchParams();
  params.set('url', path);

  // Tratamento para remover "px" se o usuário passar string
  if (width) {
    const w = String(width).replace('px', '');
    if (!isNaN(Number(w))) params.set('w', w);
  }

  if (height) {
    const h = String(height).replace('px', '');
    if (!isNaN(Number(h))) params.set('h', h);
  }

  if (quality) params.set('q', quality.toString());

  return `/_vatts/image?${params.toString()}`;
});

const baseStyle = computed<StyleValue>(() => {
  return {
    width: props.width ? (typeof props.width === 'number' ? `${props.width}px` : props.width) : 'auto',
    height: props.height ? (typeof props.height === 'number' ? `${props.height}px` : props.height) : 'auto',
  };
});

// Remove "px" para os atributos nativos width/height da tag img
const cleanDimension = (val?: string | number) => {
  if (typeof val === 'string') return val.replace('px', '');
  return val;
};
</script>

<template>
  <img
      v-bind="$attrs"
      :src="optimizedSrc"
      :alt="alt"
      :loading="priority ? 'eager' : 'lazy'"
      :decoding="priority ? 'sync' : 'async'"
      :width="cleanDimension(width)"
      :height="cleanDimension(height)"
      :style="baseStyle"
      class="vatts-image"
  />
</template>
