// docs/src/web/components/Footer.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";
import { importServer, VattsImage } from "vatts/vue";

// RPC Setup mantido como solicitado
const api = importServer<typeof import("../../backend/helper")>("../../backend/helper");
const { PackageVersion } = api;

const version = ref("1.0.0");

onMounted(async () => {
  const v = await PackageVersion();
  if (v !== null) {
    version.value = v;
  }
});
</script>

<template>
  <footer class="relative z-10 py-12 px-6 bg-[#0a0a0c]">
    <div class="max-w-7xl mx-auto">
      <div class="flex flex-col md:flex-row justify-between items-center gap-8">
        <div class="flex flex-col items-center md:items-start gap-3">
          <div class="flex items-center gap-3">
            <VattsImage
                src="/logo-all-white.png"
                alt="Vatts"
                height="28px"
                class="h-7 brightness-125 opacity-80"
            />
            <span class="hidden md:block w-px h-4 bg-white/10" />
            <div class="flex items-center gap-2 px-2.5 py-1 rounded-full bg-emerald-500/5 border border-emerald-500/20">
              <span class="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
              <span class="text-[10px] uppercase tracking-wider font-bold text-emerald-500/80">
                                v{{ version }}
                            </span>
            </div>
          </div>
          <p class="text-slate-500 text-sm max-w-xs text-center md:text-left">
            The next-generation framework for building lightning-fast web applications.
          </p>
        </div>

        <div class="flex flex-col items-center md:items-end gap-4">
          <div class="flex items-center gap-6">
            <a
                href="https://github.com/mfrazlab/vatts.js"
                target="_blank"
                rel="noopener noreferrer"
                class="text-slate-400 hover:text-white transition-all transform hover:scale-110"
            >
              <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="22"
                  height="22"
                  viewBox="0 0 496 512"
                  fill="currentColor"
              >
                <path d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"/>
              </svg>
            </a>
          </div>

          <div class="text-slate-600 text-[12px] tracking-tight font-medium">
            © {{ new Date().getFullYear() }} <span class="text-slate-400">Vatts.js</span>. Crafted by developers, for developers.
          </div>
        </div>
      </div>
    </div>
  </footer>
</template>

// docs/src/web/components/Footer.tsx
import {importServer, VattsImage} from "vatts/react";
import {FaGithub} from "react-icons/fa6";
import React, {useState} from "react";
const api = importServer<typeof import("../../backend/helper")>("../../backend/helper");
const { PackageVersion } = api;
export default function Footer() {
    const [version, setVersion] = React.useState("1.0.0")
    useState(async () => {
        const v = await PackageVersion()
        if(v !== null) {
            setVersion(v)
        }
    })
    return (
        <footer className="relative z-10 py-12 px-6 bg-[#0a0a0c]">
            <div className="max-w-7xl mx-auto">
                <div className="flex flex-col md:flex-row justify-between items-center gap-8">
                    {/* Brand & Status */}
                    <div className="flex flex-col items-center md:items-start gap-3">
                        <div className="flex items-center gap-3">
                            <VattsImage src="/logo-all-white.png" alt="Vatts" height={"28px"} className="h-7 brightness-125 opacity-80" />
                            <span className="hidden md:block w-px h-4 bg-white/10" />
                            <div className="flex items-center gap-2 px-2.5 py-1 rounded-full bg-emerald-500/5 border border-emerald-500/20">
                                <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
                                <span className="text-[10px] uppercase tracking-wider font-bold text-emerald-500/80">v{version}</span>
                            </div>
                        </div>
                        <p className="text-slate-500 text-sm max-w-xs text-center md:text-left">
                            The next-generation framework for building lightning-fast web applications.
                        </p>
                    </div>

                    {/* Social & Legal */}
                    <div className="flex flex-col items-center md:items-end gap-4">
                        <div className="flex items-center gap-6">
                            <a
                                href="https://github.com/mfrazlab/vatts.js"
                                target="_blank"
                                rel="noopener noreferrer"
                                className="text-slate-400 hover:text-white transition-all transform hover:scale-110"
                            >
                                <FaGithub size={22} />
                            </a>
                        </div>

                        <div className="text-slate-600 text-[12px] tracking-tight font-medium">
                            © {new Date().getFullYear()} <span className="text-slate-400">Vatts.js</span>. Crafted by developers, for developers.
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    )
}
