// docs/src/web/layout.vue
<script lang="ts">
import type { Metadata } from "vatts/vue";
export const metadata: Metadata = {
  title: "Vatts.js | The Fastest Framework for React",
  description: "The fastest and simplest web framework for React! Start building high-performance web applications today with Vatts.js.",
  favicon: '/logo.png',
  scripts: {
    "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2662588853991140": {
      "crossorigin": 'anonymous',
      "async": ""
    }
  }
};
</script>

<script setup lang="ts">
import './globals.css';
import { router } from 'vatts/vue'; // Necessário para identificar a mudança de página

// Equivalente ao onExitComplete={() => window.scrollTo(0, 0)}
function onAfterLeave() {
  window.scrollTo(0, 0);
}
</script>

<template>
  <Transition
      appear
      name="page-transition"
      mode="out-in"
      @after-leave="onAfterLeave"
  >
    <div :key="router.pathname" class="bg-black">
      <slot />
    </div>
  </Transition>
</template>

<style>
/* Define a duração e a curva de transição.
  cubic-bezier(0.22, 1, 0.36, 1) é a conversão CSS do ease: [0.22, 1, 0.36, 1]
*/
.page-transition-enter-active,
.page-transition-leave-active {
  transition: opacity 0.3s, transform 0.3s, filter 0.3s;
  transition-timing-function: cubic-bezier(0.22, 1, 0.36, 1);
}

/* Estado inicial de entrada (hidden) e final de saída (exit).
  opacity: 0, scale: 0.98, filter: blur(5px)
*/
.page-transition-enter-from,
.page-transition-leave-to {
  opacity: 0;
  transform: scale(0.98);
  filter: blur(5px);
}

/* Estado ativo (enter) é o padrão do elemento, então não precisa declarar explicitamente o 'to' */
</style>

// docs/src/web/layout.tsx
import React from 'react';
import {Metadata, router} from "vatts/react"
import './globals.css';
import {AnimatePresence, motion} from "framer-motion";
import 'prismjs/themes/prism-tomorrow.css'; // Tema escuro do Prism
interface LayoutProps {
    children: React.ReactNode;
}

export const metadata: Metadata = {
    title: "Vatts.js | The Fastest Framework for React",
    description: "The fastest and simplest web framework for React! Start building high-performance web applications today with Vatts.js.",
    favicon: '/logo.png',
    scripts: {
        "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2662588853991140": {
            "crossorigin": 'anonymous',
            "async": ""
        }
    }
};

export default function Layout({ children }: LayoutProps) {
    // Animação Modernizada: Leve escala (zoom in/out) com desfoque
    const variants = {
        hidden: { opacity: 0, scale: 0.98, filter: "blur(5px)" },
        enter: { opacity: 1, scale: 1, filter: "blur(0px)" },
        exit: { opacity: 0, scale: 0.98, filter: "blur(5px)" },
    };

    return (
        <AnimatePresence
            mode="wait"
            onExitComplete={() => window.scrollTo(0, 0)}
        >
            <motion.div
                key={router.pathname}
                variants={variants}
                initial="hidden"
                animate="enter"
                exit="exit"
                // Curva de transição mais fluida e um pouco mais rápida
                transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}
                className={"bg-black"}
            >
                {children}
            </motion.div>
        </AnimatePresence>
    );
}
